### ISSUE TITLE
[BUG] Quanvolution demo results don't match rendered version

### ISSUE THREAD

**Issue by glassnotes** [PennyLaneAI/qml#257]
First noted by a user [here](https://discuss.pennylane.ai/t/not-getting-the-expected-results/986), and confirmed independently by me using a fresh environment with the most recent version of PennyLane and contents of the `qml` repo requirements file.

The plots produced at the end (left) don't match the results in the demo (right). The user obtained identical plots to my locally run version (given this, and the consistency of the results, the issue doesn't appear to be one that stems from random seeds or anything). 

![image](https://user-images.githubusercontent.com/2068515/115576402-757cc180-a291-11eb-9ac0-221f875c5a53.png)

**Comment by josh146** [comment]
My first guess was that this was a non-executed demo, but it looks like it _is_ executed 🤔

**Comment by glassnotes** [comment]
> My first guess was that this was a non-executed demo, but it looks like it _is_ executed thinking

Yes, same here. Do you get different results as well when you run it locally?

**Comment by josh146** [comment]
Might not get a chance currently! Will pencil it in as a todo. I wonder if this is related to @co9olguy's numerical accuracy issue. @glassnotes, if you run the PL test suite locally, does everything pass?

**Comment by glassnotes** [comment]
It actually does not - I get a few failures (noted below), but nothing I would expect to affect the results of the demo execution.

```
FAILED tests/test_about.py::test_about - AssertionError: assert '0.16.0.dev' in '0.15.0.dev0'
FAILED tests/circuit_graph/test_qasm.py::TestQASMConformanceTests::test_agrees_qiskit_plugin - pkg_resources.VersionConflict: (Penn...
FAILED tests/circuit_graph/test_qasm.py::TestQASMConformanceTests::test_basis_state_agrees_qiskit_plugin - pkg_resources.VersionCon...
FAILED tests/math/test_functions.py::test_conj[t5] - TypeError: loop of ufunc does not support argument 0 of type ResourceVariable ...
```

**Comment by glassnotes** [comment]
Just ran locally, yes it does. The results in this graph are consistent with the previous version I obtained running locally, which is still inconsistent with the live demo.

![image](https://user-images.githubusercontent.com/2068515/137314809-195b99c0-83f3-431b-885d-546e758287eb.png)

**Comment by KetpuntoG** [comment]
It seems that this problem has been solved. 
I have run the notebook in Google Colab and this is my output
<img width="514" alt="Captura de Pantalla 2022-11-24 a las 15 28 06" src="https://user-images.githubusercontent.com/65235481/203859429-837f8b63-37a4-4a36-83ba-c7d266a7f565.png">

In the demo seems the same:

<img width="542" alt="Captura de Pantalla 2022-11-24 a las 15 28 26" src="https://user-images.githubusercontent.com/65235481/203859475-65b207a9-8eb1-4c10-89fe-02d387be2b38.png">

**Comment by josh146** [comment]
@KetpuntoG nice! Although I suppose the mystery is not solved, as your results show classical training beating the quantum training, which isn't what the demo originally showed

**Comment by KetpuntoG** [comment]
seems very dependent on the seed. If we want something that quantum "wins", we can put seed 42 although I'm not a big fan of these things

<img width="448" alt="Captura de Pantalla 2022-11-24 a las 17 20 06" src="https://user-images.githubusercontent.com/65235481/203869815-c9dd0ecd-41e3-49a8-9445-3f0d3b195020.png">

**Comment by josh146** [comment]
Yeah, I would say this is maybe more an issue with the conclusion of the demo, rather than a seed issue

**Comment by krishnendurajesh** [comment]
I’d be happy to work on this. I think the demo’s conclusion could be updated to reflect that the results are seed-dependent and that classical training can outperform the quantum model in this example. Could you assign this issue to me?
